#!/usr/bin/python3
# SPDX-FilecopyrightText: 2023 Ryotaro Karikomi ryotaro.karikomi@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

w, h = input().split()
weight = float(w)
height = float(h) / 100
    

BMI = round(weight / pow(height, 2), 2)
print(BMI)
