#!/usr/bin/python3
# SPDX-FilecopyrightText: 2023 Ryotaro Karikomi ryotaro.karikomi@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

while True:
  try:
    w = input("Input your body weight[kg] >")
    weight = float(w)
    break
  except EOFError as e:
    print(e)
    break
  except ValueError as e:
    print(e)

while True:
  try:
    h = input("Input your height[cm] >")
    height = float(h)
    break
  except EOFError as e:
    print(e)
    break
  except ValueError as e:
    print(e)

print("weight:", weight, "[kg]")
print("height:", height, "[cm]")
