#!/usr/bin/python3
# SPDX-FilecopyrightText: 2023 Ryotaro Karikomi ryotaro.karikomi@gmail.com
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = [0, 1]

for line in sys.stdin:
  try:
    ans[0] += int(line)
    ans[1] *= int(line)
  except:
    ans[0] += float(line)
    ans[1] *= float(line)

for a in ans:
  print(a,end=' ')
print()
